version: '3.1'
  
services:

  #
  # Reverse proxy SSL
  #
  rp:
    image: jonesbusy/nginx-ssl-rp:latest
    build:
      context: .
    restart: always
    container_name: nginx
    volumes:
      - /etc/ssl/cert.crt:/etc/ssl/cert.crt
      - /etc/ssl/key.pem:/etc/ssl/key.pem
    environment:
      server_host: "test.example.com"
      backend_host: "my-backend"
      backend_port: 8080
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"

#
# Networking
#
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"    
    ipam:
      driver: default
